### ISSUE TITLE
Enjoyed the histogram article.  Could I get access to the entire data set of marathon runners?

### ISSUE THREAD

**Issue by hathawayj** [AmeliaMN/histogram_essay#4]
I see the random sample of 3000 which will be useful.  I wonder if there is a way to get the entire set from you?

**Comment by AmeliaMN** [comment]
Sorry, I thought we had linked the full data somewhere! We sampled from [this](http://faculty.chicagobooth.edu/george.wu/research/marathon/data.htm) data set.
